import assert from 'node:assert/strict';
import {blank,AGES,KINS,PROFESSIONS,GENERAL,SKILLS,attrCap,skillCap,budgets,normalize,resetProfession,validateImport,resources,encumbrance,paths,money} from '../public/tools/rules.js';
let checks=0;function check(fn){fn();checks++;}
for(const kin of Object.keys(KINS))for(const profession of Object.keys(PROFESSIONS))for(const age of Object.keys(AGES))check(()=>{let s=blank();s.expansion='bitter';s.kin=kin;s.age=age;resetProfession(s,profession);normalize(s);assert.equal(s.age,kin==='elf'?'adult':age);for(const id of ['str','agi','wit','emp'])assert.equal(attrCap(s,id),4+Number(KINS[kin].key===id)+Number(PROFESSIONS[profession].key===id));for(const [id] of SKILLS)assert.equal(skillCap(s,id),PROFESSIONS[profession].skills.includes(id)?3:1);const copy=validateImport(JSON.parse(JSON.stringify(s)));assert.deepEqual(copy,s);});
check(()=>{const s=blank();s.attrs={str:5,agi:4,wit:2,emp:4};s.skills={...s.skills,melee:3,might:3,endure:2};s.talents={packrat:1};s.trade=['rope'];s.name='Тар';s.pride='Никогда не теряю след.';s.secret='Скрыл долг.';assert.deepEqual(budgets(s),{attrs:0,skills:0,talents:0});assert.deepEqual(validateImport(s),s);});
check(()=>{let s=blank();s.kin='halfelf';s.age='adult';resetProfession(s,'sorcerer');s.attrs={str:3,agi:3,wit:5,emp:3};s.skills.melee=1;s.skills.craft=2;s.skills.lore=3;s.skills.insight=2;s.skills.influence=2;s.path='blood';s.pathRank=2;s.talents.lightning=1;assert.deepEqual(budgets(s),{attrs:0,skills:0,talents:0});validateImport(s);s.pathRank=3;assert.throws(()=>validateImport(s));});
check(()=>{let s=blank();s.kin='dwarf';assert.equal(attrCap(s,'str'),6);s.attrs.str=6;s.attrs.agi=4;s.attrs.wit=3;s.attrs.emp=2;s.skills.melee=3;s.skills.might=3;s.skills.endure=2;resetProfession(s,'sorcerer');assert.equal(s.attrs.str,5);assert.ok(s.skills.melee<=1);s.age='old';normalize(s);assert.ok(budgets(s).attrs>=0);});
check(()=>{const s=blank();s.trade=['rations'];assert.equal(resources(s).food,10);s.trade=['torches'];assert.equal(resources(s).torches,6);assert.equal(encumbrance(s).used,4.5);});
check(()=>{const s=blank();s.attrs.str=99;assert.throws(()=>validateImport(s));const t=blank();t.kin='__proto__';assert.throws(()=>validateImport(t));const u=blank();u.skills.melee=4;assert.throws(()=>validateImport(u));const v=blank();v.talents.lightning=2;v.pathRank=2;assert.throws(()=>validateImport(v));});
check(()=>{const s=blank();s.expansion='bitter';resetProfession(s,'champion');s.coins=12;assert.equal(resources(s).torches,6);validateImport(s);s.expansion='core';normalize(s);assert.equal(s.profession,'fighter');});
check(()=>{const s=blank();resetProfession(s,'druid');assert.equal(paths(s).length,3);s.expansion='bitter';assert.equal(paths(s).length,4);s.path='ice';s.expansion='core';normalize(s);assert.notEqual(s.path,'ice');});
check(()=>{const s=blank();s.coins=3;s.purchases=['flint'];assert.deepEqual(money(s),{total:30,spent:2,remaining:28});validateImport(s);s.purchases=['broadsword'];assert.throws(()=>validateImport(s));});
check(()=>{const s=blank();s.talents.packrat=1;assert.equal(encumbrance(s).max,6);s.age='adult';s.talents.packrat=2;assert.equal(encumbrance(s).max,9);s.coins=6;s.purchases=['rations'];assert.equal(resources(s).food,10);});
console.log(`${checks} rule checks passed (${GENERAL.length} general talents).`);
